<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <UserSecretsId>02dc577b-a38d-499e-8294-8bad4949108d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SkiaSharp" Version="4.152.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.152.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\Fonts\*.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\Data\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
